### ISSUE TITLE
'takeover' :-)

### ISSUE THREAD

**Issue by ChristianWeyer** [synacktraa/tool-parse#3]
Very nice lib! Thank you!

... one question, though:
Why name the decorator 'takeover'?

**Comment by synacktraa** [comment]
> Very nice lib! Thank you!
> 
> 
> 
> ... one question, though:
> 
> Why name the decorator 'takeover'?

Thank you! I’m glad you like the library!

Regarding your question about the ‘takeover’ decorator, I named it that way just to add a bit of drama and fun 😂

**Comment by synacktraa** [comment]
> Very nice lib! Thank you!
> 
> 
> 
> ... one question, though:
> 
> Why name the decorator 'takeover'?

In next version, it will be renamed to 'register'. A lot of people are confused by the name 'takeover'🙂

**Comment by synacktraa** [comment]
@ChristianWeyer Hey, `hypertion` has been replaced by `tool-parse` library, it now supports registering functions(both synchronous/asynchronous), `pydantic.BaseModel`, `typing.TypedDict` and `typing.NamedTuple`. Thanks!
