### ISSUE TITLE
suggestion: rename pypi artifact to be more specific

### ISSUE THREAD

**Issue by anthonywu** [synacktraa/tool-parse#4]
# suggestion

For sake of making dependent projects' `pip freeze` more self explanatory, I suggest using a more specific pypi artifact name such as `llm-tool-parse` or similar.

## context

I was TL/admin on many Python projects. Naming artifacts well helps with discoverability (e.g. when someone greps text output, and avoids vague/ambiguous interpretation of your library's utility: `tool` and `parse` are overloaded terminology in software.

**Comment by synacktraa** [comment]
You're correct, even my previous project hypertion(only supported regular functions) didn't make sense to anyone because of how I named it.🙂

**Comment by anthonywu** [comment]
there's always a push/pull between:

1. being "cute" vs. being "literal" with project names
2. being "literal" and tightly scoped vs. "vague" and open to empire building

good luck with the next phases of development, I was going to continue my Ollama PR 238 by adding a registry, but I would also tightly scope that to building a dictionary of Callables, and just helping users look that up.

Anything that's more opinionated than that probably belongs in a side library like this one.

**Comment by synacktraa** [comment]
@anthonywu I am confused, please suggest some names🙂
